### ISSUE TITLE
Filter Box Hieght

### ISSUE THREAD

**Issue by theryankelly** [MAPC/trailmap3#1]
User need to be able to select and see all components of filter box.  Currently being cut off at small screen heights.

<img width="617" alt="Screen Shot 2019-08-29 at 11 20 05 AM" src="https://user-images.githubusercontent.com/2421382/63953351-2d22e700-ca4f-11e9-9472-a1b1d0836068.png">

We may consider adding a scroll for small height viewports.

**Comment by theryankelly** [comment]
In testing on mobile this current height is not responsive and is too small. Not functioning as a menu overlay of map.

**Comment by theryankelly** [comment]
September 12 screenshot of issue above
![Screenshot_20190912-101003](https://user-images.githubusercontent.com/2421382/65172465-f707d000-da1a-11e9-97ad-5c18f920b80f.png)

**Comment by theryankelly** [comment]
Same view today
![Screenshot_20190918-134322](https://user-images.githubusercontent.com/2421382/65172490-071faf80-da1b-11e9-8d7d-d7c05d995f51.png)

Size no longer an issue but it overlaps with toggle and search.  The toggle does not toggl on and off the menu.

**Comment by mzagaja** [comment]
Which Android are you using? Currently is not reproducing on Chrome or Safari inspectors of my physical iPhone device:
<img width="550" alt="image" src="https://user-images.githubusercontent.com/565647/65173522-f2dcb200-da1c-11e9-9c6d-90a15f0f9cab.png">

<img width="738" alt="image" src="https://user-images.githubusercontent.com/565647/65173570-10aa1700-da1d-11e9-8280-3105e2c210b8.png">

Also not reproducing on a Pixel 2 device (via BrowserStack live testing)

<img width="707" alt="image" src="https://user-images.githubusercontent.com/565647/65173857-bbbad080-da1d-11e9-9885-bc62cd85a07c.png">
