### ISSUE TITLE
Add Map Scale

### ISSUE THREAD

**Issue by dloutzenheiser** [MAPC/trailmap3#17]
There needs to be a scale somewhere on the map.

**Comment by theryankelly** [comment]
https://docs.mapbox.com/mapbox-gl-js/api/#Scale

**Comment by mzagaja** [comment]
This is not supported by the React component/library yet so I would need to manually build and link it up. Probably a couple days of work to do this one. Supported controls are listed at https://github.com/uber/react-map-gl/tree/2d9b93293dbc64dccdcf392e9f1bbfd15983ba69/docs/components

**Comment by atomtay** [comment]
Resolved in commit [ac36ba6](https://github.com/MAPC/trailmap3/commit/ac36ba6c29995bf9f752639f906200c210bff4e7) with reference to `componentDidMount` to update map object. I found [this ReactMapGL issue response](https://github.com/uber/react-map-gl/issues/197#issuecomment-361076360) to be particularly helpful in getting the scale to render.
