### ISSUE TITLE
Toggle Button Selection

### ISSUE THREAD

**Issue by theryankelly** [MAPC/trailmap3#2]
Toggle button should be clickable and function to turn on and off layers.  Clicking anywhere in the image, text, box and especially button itself should trigger the selection.

<img width="158" alt="Screen Shot 2019-08-29 at 11 25 24 AM" src="https://user-images.githubusercontent.com/2421382/63953632-b6d2b480-ca4f-11e9-8671-cc28327800ef.png">

**Comment by mzagaja** [comment]
Resolved in https://github.com/MAPC/trailmap3/commit/76f94eb966fd0e9c0aaf3da303525978b45f7a3a
