### ISSUE TITLE
Add Footrails Layer

### ISSUE THREAD

**Issue by dloutzenheiser** [MAPC/trailmap3#21]
1) Need to add "Foot Trails" under the protected pathways header

2)  add a separate category for the LandLine layer

**Comment by theryankelly** [comment]
Footrails layer is currently large file that hinders performance has been kept off in development. Decision has been made to add it back into protected pathways parent section.

**Comment by atomtay** [comment]
Resolved with commit [b4ac9e7](https://github.com/MAPC/trailmap3/commit/b4ac9e74f2935dee17cb416c95abd32574f0a926)
