### ISSUE TITLE
Tab Name and Icon

### ISSUE THREAD

**Issue by theryankelly** [MAPC/trailmap3#36]
Should switch current talbe name to MAPC Trailmap form Trailmap 3.  Also should make and add a browser icon.

<img width="96" alt="Screen Shot 2019-10-28 at 3 56 29 PM" src="https://user-images.githubusercontent.com/2421382/67713203-c01ec580-f99b-11e9-92bf-63704f37de7e.png">

**Comment by atomtay** [comment]
Partially resolved in #61 (tab name updated, but we're still using the default favicon)
