### ISSUE TITLE
Parent Selector Functionality

### ISSUE THREAD

**Issue by theryankelly** [MAPC/trailmap3#4]
The parent selectors "Protected Pathways", "Separate Lanes" and Shared Roadways" should toggle on and off all child selectors.   

Parent selector (color + toggle) should turn on when any selections are chosen.  Parent selector  (color + toggle) should turn off when a no selections chosen

**Comment by atomtay** [comment]
Resolved in commit [ae1d6d6](https://github.com/MAPC/trailmap3/commit/ae1d6d6100f0de134803e634367e1092baa9a08b)
