### ISSUE TITLE
Provide Download Link

### ISSUE THREAD

**Issue by theryankelly** [MAPC/trailmap3#43]
Need to add back in a link to download the data/shapefile.  Would like to have this feed from DataCommon.  Currently links on DataCommon have the layers in separate files: https://datacommon.mapc.org/browser/datasets/356

**Comment by atomtay** [comment]
There's a few ways we can approach this; any preferences?
- Separate links to each of the three Datacommon datasets ([Shared Used](https://datacommon.mapc.org/browser/datasets/404),[Walking](https://datacommon.mapc.org/browser/datasets/382), and [Bicycle Facilities](https://datacommon.mapc.org/browser/datasets/356))
- One link to download one combined file
- One link to download three separate files simultaneously
- Might even be able to do one link to download the trails currently displayed, but not 200% sure

Also, should there be down CSV and Shapefile downloads?

**Comment by theryankelly** [comment]
Link to use for download: https://datacommon.mapc.org/browser/Transportation/Bicycle%20and%20Pedestrian%20Facilities

**Comment by atomtay** [comment]
So would that follow text like "To find the CSV and Shapefiles for these trails, visit [MAPC's Datacommon](https://datacommon.mapc.org/browser/Transportation/Bicycle%20and%20Pedestrian%20Facilities)"?

**Comment by atomtay** [comment]
Resolved in PR #59
