### ISSUE TITLE
Add Aerial and OSM Layers

### ISSUE THREAD

**Issue by theryankelly** [MAPC/trailmap3#45]
Related to #15

Add in two additional map layers – aerial and openstreetmap.  
Need to chose layer styles, but note from David- "I am just fine with the data linework being optimized for the existing map layers, and maybe not so for aerial and OSM" 

Potential layers (https://www.mapbox.com/maps/satellite/ and https://www.mapbox.com/maps/streets/

**Comment by atomtay** [comment]
Resolved in PR #54
