### ISSUE TITLE
Remove Bounding Box

### ISSUE THREAD

**Issue by theryankelly** [MAPC/trailmap3#6]
Parent selectors should not have square bounding box outline on selection.  

![image](https://user-images.githubusercontent.com/2421382/63962762-7b40e600-ca61-11e9-8e8c-91a5b99fadf0.png)

**Comment by atomtay** [comment]
Resolved in commit [ff39fed](https://github.com/MAPC/trailmap3/commit/ff39fedba8e24f13775cb25bb96883d992f2e7ba)
